title: Mudit Agarwal
logo: "/Mudit.png"
description: >
  <br>
  Full Stack Developer | Frontend Engineer
  <br>
  <a href="https://www.linkedin.com/in/mudit-agarwal-a9a9341b6/">
    <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="mailto:muditagarwalna@gmail.com">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>
theme: jekyll-theme-minimal
